/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Codigo = string;
export type CodEan = string;
export type Ean14 = string;
export type Nombre = string;
export type Linea = string;
export type Peso = number;
export type StockReferencial = number;
export type PrecioReferencial = number | null;
export type CantidadPorCaja = number | null;
export type Keywords = string[];
export type Cantidad = number;
export type Observaciones = string | null;
export type Precios = {
  [k: string]: number;
} | null;
export type List = ProductoEditado[];
export type Nombre1 = string;
export type Correo = string;
export type Tipo = string;
export type Documenttype = string | null;
export type Cliente = string | null;
export type DocumentoCliente = string | null;
export type CodigoCliente = string | null;
export type Fecha = string | null;
export type Marca1 = string | null;
export type Marca2 = string | null;
export type Marca3 = string | null;
export type Marca4 = string | null;
export type Marca5 = string | null;
export type Sucursal = string | null;
export type Montooriginal = number | null;
export type DatosGenerales = string | null;
export type DistribucionPrecios = string | null;
export type TarjetasProductos = string[] | null;
export type DashboardImage = string | null;

export interface PreciosExport {
  list: List;
  usuario: Usuario;
  tipo: Tipo;
  form: Form;
  datos_generales?: DatosGenerales;
  distribucion_precios?: DistribucionPrecios;
  tarjetas_productos?: TarjetasProductos;
  dashboard_image?: DashboardImage;
  [k: string]: unknown;
}
export interface ProductoEditado {
  codigo: Codigo;
  cod_ean: CodEan;
  ean_14: Ean14;
  nombre: Nombre;
  linea: Linea;
  peso: Peso;
  stock_referencial: StockReferencial;
  precio_referencial?: PrecioReferencial;
  cantidad_por_caja?: CantidadPorCaja;
  keywords: Keywords;
  cantidad: Cantidad;
  observaciones?: Observaciones;
  precios?: Precios;
  [k: string]: unknown;
}
export interface Usuario {
  nombre: Nombre1;
  correo: Correo;
  [k: string]: unknown;
}
export interface Form {
  documentType?: Documenttype;
  cliente?: Cliente;
  documento_cliente?: DocumentoCliente;
  codigo_cliente?: CodigoCliente;
  fecha?: Fecha;
  marca1?: Marca1;
  marca2?: Marca2;
  marca3?: Marca3;
  marca4?: Marca4;
  marca5?: Marca5;
  sucursal?: Sucursal;
  montoOriginal?: Montooriginal;
  [k: string]: unknown;
}
